#Email Automatically Finding -Part-I
# #email format from rocket reach
import time
try: 
    from googlesearch import search 
except ImportError:  
    print("No module named 'google' found") 
def method(dummyquery):
    domain=str(dummyquery)
    query = str(dummyquery+' email rocketreach')
    for j in search(query, tld="co.in", num=1, stop=1, pause=4): 
        #print(j)
        import requests
        page = requests.get(j)

        if "first last_initial" in page.text:
            print("first last_initial	"+" "+domain)
        elif "first_initial last" in page.text:
            print("first_initial last"+" "+domain)
        elif "last first_initial" in page.text:
            print("last first_initial"+" "+domain)
        elif "first last" in page.text:
            print("first last"+" "+domain)
        elif "first" in page.text:
            print("first"+" "+domain)
        elif "last" in page.text:
            print("last"+" "+domain)
        elif "first '.' last" in page.text:
            print("first '.' last"+" "+domain)
        elif "first '-' last" in page.text:
            print("first '-' last	"+" "+domain)
        else:	
            print("no"+domain)	
'''method("dtlr.com")
method("dailysale.com")
method("smokecartel.com")
method("calpaktravel.com")
method("novelkeys.xyz")
time.sleep(10)
method("nativecos.com")
method("credobeauty.com")
method("fearofgod.com")
method("krisnations.com")
method("buckmason.com")
time.sleep(15)
method("trueleafmarket.com")
method("hismileteeth.com")
method("noteshop.co.uk")
method("getkeysmart.com")
method("cartots.com")
method("bollandbranch.com")
time.sleep(10)
method("vapordna.com")
method("misen.com")
method("thrivecausemetics.com")
method("lovevery.com")
method("rayconglobal.com")
method("pax.com")
time.sleep(10)
method("infograpia.com")
method("weareunderground.com")
method("us.hismileteeth.com")
method("uk.hismileteeth.com")
method("whitefoxboutique.com")
method("naadam.co")
time.sleep(15)
method("craftdlondon.com")
method("tommyjohn.com")
method("richardsonshop.com")
method("secretlab.eu")
method("fleshlight.com")
method("yogaoutlet.com")
time.sleep(10)
method("italystation.com")
method("nobullproject.com")
method("bcbg.com")
method("ralphchristian.com")
method("statusanxiety.com.au")
method("untuckit.com")
time.sleep(10)
method("the4.co")
method("vapor.com")
method("brinkerandeliza.com")'''
method("drjoedispenza.com")
method("tula.com")
method("rhinoshield.io")
time.sleep(15)
method("gaiam.com")
method("shoepalace.com")
method("blenderseyewear.com")
method("47brand.com")
method("merchology.com")
time.sleep(10)
method("leons.ca")
method("brumate.com")
method("undergroundshirts.com")
method("thehouseofdrew.com")
method("shoppremiumoutlets.com")
method("golfwang.com")
time.sleep(20)
method("establishedtitles.com")
method("stateofescape.com")
method("teelaunch.com")
method("creality3dofficial.com")
method("ember.com")
method("gldn.com")
time.sleep(10)
method("byteme.com")
method("nixplay.com")
method("32degrees.com")
method("publicdesire.com")
method("theproscloset.com")
time.sleep(15)
method("gochirp.com")
method("magicspoon.com")
method("boombycindyjoseph.com")
method("harpercollins.com")
method("ellebabe.com")
method("chubbiesshorts.com")
method("anycubic.com")
method("tesmanian.com")
method("turtlebeach.com")
time.sleep(10)
method("woowlish.com")
method("barnerbrand.com")
method("savannahs.com")
method("thehappyplanner.com")
method("sodastream.com")
time.sleep(15)
method("independenttradingco.com")
method("shethinx.com")
method("bajaao.com")
method("marinelayer.com")
method("sakara.com")
method("bando.com")
time.sleep(10)
method("volcom.com")
method("fast-growing-trees.com")
method("2modern.com")
method("bungiestore.com")
method("qtrove.com")
method("monivation.com")
time.sleep(15)
method("alohas.io")
method("sandmarc.com")
method("getit.qa")
method("corkcicle.com")
method("helixsleep.com")
method("langehair.com")
time.sleep(15)
method("deadstock.ca")
method("organifishop.com")
method("ekster.com")
method("qbedding.com")
method("maisondefashion.com")
method("croveshop.com")
time.sleep(10)
method("thelittlemarket.com")
method("manduka.com")
method("mensluxuryboutique.com")
method("losangelesapparel.net")
method("eightvape.com")
method("verabradley.com")
method("stuhrling.com")
time.sleep(15)
method("huhstore.com")
method("100percentpure.com")
method("spartan.com")
method("blissy.com")
method("ninewest.com")
time.sleep(10)
method("naturallife.com")
method("apt2b.com")
method("shopcarolinagirls.com")
method("ghospell.com")
method("collins.co.uk")
method("xoticpc.com")
time.sleep(10)
method("fahertybrand.com")
method("onewheel.com")
method("stio.com")
method("phonesoap.com")
method("loomsolar.com")
method("4patriots.com")
time.sleep(15)
method("gfore.com")
method("the-citizenry.com")
method("bhfo.com")
method("shopthemint.com")
method("bape.com")
method("beardbrand.com")
time.sleep(10)
method("case-mate.com")
method("shopvida.com")
method("indestructibleshoes.com")
method("ronherman.com")
method("jawzrsize.com")
method("vergegirl.com")
time.sleep(20)
method("leesa.com")
method("kjbeckett.com")
method("youtooz.com")
method("knockaround.com")
method("rdserviceonline.com")
time.sleep(10)
method("astitchahalf.net")
method("lumecube.com")
method("american-giant.com")
method("function18.com")
method("packagefreeshop.com")
time.sleep(10)
method("epicland.com.mx")
method("hypop.com.au")
method("motiondesign.school")
method("shinesty.com")
method("cozyearth.com")
method("windsorstore.com")
time.sleep(10)
method("echelonfit.com")
method("ghostlifestyle.com")
method("thepangaia.com")
method("carawayhome.com")
method("puffy.com")
method("mypatriotsupply.com")
time.sleep(10)
method("warmlydecor.com")
method("teddyfresh.com")
method("tiege.com")
method("minecraftshop.com")
method("thecoutureclub.com")
method("propshop24.com")
time.sleep(15)
method("iamgia.com")
method("nuggetcomfort.com")
method("bluemercury.com")
method("lootcrate.com")
method("1stphorm.com")
method("biossance.com")
method("goodamerican.com")
method("lightroompresets.com")
time.sleep(10)
method("representclo.com")
method("scandinaviandesigns.com")
method("petboutique.co")
method("smartsaker.com")
method("quayaustralia.com")
method("vrai.com")
method("oneill.com")
time.sleep(15)
method("loungeunderwear.com")
method("soundstrue.com")
method("sunwarrior.com")
method("residenthome.com")
method("taotronics.com")
method("mykitsch.com")
time.sleep(10)
method("railsclothing.com")
method("pinklily.com")
method("joovv.com")
method("auratenewyork.com")
method("whogivesacrap.org")
method("vegamour.com")
method("lakenzie.com")
time.sleep(15)
method("prxperformance.com")
method("matadorup.com")
method("ine.com")
method("taijewelry.com")
method("timbuk2.com")
method("jeffreestarcosmetics.com")
method("cupshe.com")
time.sleep(10)
method("firebox.com")
method("fanjoy.co")
method("under510.com")
method("sophiebuhai.com")
method("smets.lu")
method("pzdeals.com")
time.sleep(10)
method("echt.com.au")
method("blueland.com")
method("foco.com")
method("pratajoyeria.com")
method("efavormart.com")
method("grupodecme.com")
time.sleep(15)
method("alexandani.com")
method("motelrocks.com")
method("luxyhair.com")
method("wildone.com")
method("happiestbaby.com")
method("trueclassictees.com")
method("glamnetic.com")
time.sleep(10)
method("teefury.com")
method("lttstore.com")
method("groupthought.com")
method("lagarconne.com")
method("tanotis.com")
method("kravebeauty.com")
time.sleep(15)
method("notre-shop.com")
method("creativebooster.net")
method("beyondyoga.com")
method("modernindigo.com")
method("pixiemarket.com")
method("unitedbyblue.com")
method("commonthreadco.com")
time.sleep(10)
method("tentree.com")
method("suta.in")
method("harney.com")
method("knackshops.com")
method("unique-vintage.com")
method("gouletpens.com")
time.sleep(15)
method("elevatedfaith.com")
method("donjr.com")
method("sivanaspirit.com")
method("tenthousand.cc")
method("westandwillow.com")
method("flatspot.com")
method("cendre.com.au")
time.sleep(10)
method("drunkelephant.com")
method("worldwidecyclery.com")
method("bokksu.com")
method("universalstandard.com")
method("nomatic.com")
method("ugreen.com")
method("moonmagic.com")
time.sleep(15)
method("themancompany.com")
method("shopgirlscrew.com")
method("diffeyewear.com")
method("bjjfanatics.com")
method("meowingtons.com")
method("crossrope.com")
time.sleep(10)
method("thecriticalslidesociety.com")
method("dagnedover.com")
method("pinkblushmaternity.com")
method("bestsellrz.com")
method("elegantautoretail.com")
method("sparklytrees.com")
method("enchroma.com")
time.sleep(15)
method("novanym.com")
method("plumgoodness.com")
method("summersalt.com")
method("4ocean.com")
method("headsupfortails.com")
method("infograpify.com")
time.sleep(15)
method("tigermist.com.au")
method("oznico.com")
method("rains.com")
method("neonbeach.com")
method("gruntstyle.com")
method("cosette.com.au")
method("promescent.com")

#second code
'''import requests
def mail_format(domain,fname,lname):
    
    j="https://www.google.com/search?source=hp&ei=gMDNX-DaK8CM4-EP7Y-xyA4&q=@"+domain+"  email"
    page = requests.get(j)
    if "first last_initial" in page.text:
        print("first last_initial	")
        print(fname,lname[0]+'@'+domain)
    elif "first_initial last" in page.text:
        print("first_initial last")
        print(fname[0],lname+'@'+domain)
    elif "last first_initial" in page.text:
        print("last first_initial")
        print(lname,fname+'@'+domain)
    elif "first last" in page.text:
        print("first last")
        print(fname,lname+'@'+domain)
    elif "first" in page.text:
        print("first")
        print(fname+'@'+domain)
    elif "last" in page.text:
        print("last")
        print(lname+'@'+domain)
    elif "first '.' last" in page.text:
        print("first '.' last")
        print(fname+'.'+lname+'@'+domain)
    elif "first '-' last" in page.text:
        print("first '-' last	")
        print(fname+'-'+lname+'@'+domain)
    else:	
        print("no")	
mail_format("jcrew.com","Jan","Singer")'''


   






   




