try: 
    from googlesearch import search 
    import time
except ImportError:  
    print("No module named 'google' found") 
  
# to search 
def linkedin_search(domain):
    query=domain+" "
    #query = "Geeksforgeeks"
    for j in search(query, tld="co.in", num=1, stop=1, pause=7): 
        print(j)
linkedin_search("iadmireyou")
linkedin_search("Zera Jewels")
linkedin_search("Toolucky")
linkedin_search("Raven Born")
linkedin_search("Zone Amazon")
time.sleep(20)
linkedin_search("Instant Arẹ̀wà Hair")
linkedin_search("The New Breath")
linkedin_search("Tribal Gems")
linkedin_search("TCMAX")
linkedin_search("GiftBoxLondon")
time.sleep(20)
linkedin_search("Univers Dinosaure")
linkedin_search("TrendzMerch")
linkedin_search("One Stop Java Shop")
linkedin_search("Izivie")
linkedin_search("Beautylet Store")
time.sleep(20)
linkedin_search("harraqmarket")
linkedin_search("Lcj6")
linkedin_search("Inside My Vax")
linkedin_search("Lodelys")
linkedin_search("The Force Shop")
linkedin_search("Theaubergines")
time.sleep(20)
linkedin_search("Kewlioo")
linkedin_search("Overture Products")
linkedin_search("Runspree")
linkedin_search("Cable404")
linkedin_search("Abs Moto Fairings")
time.sleep(20)
linkedin_search("Minhhai")
linkedin_search("Corkcicle")
linkedin_search("Lotus Rose Boutique")
linkedin_search("Entropy Accesorioa")
linkedin_search("Custom Soccer Jerseys")
linkedin_search("JustStuffISell.com")
time.sleep(20)
linkedin_search("Danes")
linkedin_search("Fanny Pack Shoppe")
linkedin_search("Freedom Travel Gear")
linkedin_search("Thecolorsage")
linkedin_search("Vivien Yeo's Beauty Store")
linkedin_search("Lovs")
time.sleep(20)
linkedin_search("Divaslounge Online")
linkedin_search("Take It Global Sdn Bhd")
linkedin_search("manzanasegura")
linkedin_search("The365SurvivalStore")
linkedin_search("PoreCleanser Pro")
linkedin_search("BLËRN")
time.sleep(20)
linkedin_search("OakHousehold")
linkedin_search("smilezonly")
linkedin_search("Bagilio")
linkedin_search("Amor Bear")
linkedin_search("Natural Lice Products")
time.sleep(20)
linkedin_search("FreakyPet")
linkedin_search("Massivebest")
linkedin_search("Naughty By Nature Adult Store")
linkedin_search("Mbkplanners")
linkedin_search("Limette Swimwear")
linkedin_search("Gearbuyz")
