'''from bs4 import BeautifulSoup
import requests
url="https://www.liforme.com"
page=requests.get(url)
soup=BeautifulSoup(page.content,"html.parser")
for i in soup.find_all('a', href=True):
    print ("Found the URL:", i['href'])'''
import time
try: 
    from googlesearch import search 
    import time
except ImportError:  
    print("No module named 'google' found") 
  
# to search 
def linkedin_search(domain):
    query=domain+" "
    #query = "Geeksforgeeks"
    for j in search(query, tld="co.in", num=1, stop=1, pause=7): 
        print(j)


linkedin_search("Farouk  Merzougui  Native Union linkedin")
linkedin_search("benjamin  Bolognini  BYLT Basics linkedin")
linkedin_search("Holle   Dyonisio  BYLT Basics linkedin")
linkedin_search("armand  Austin  Vincero Watches linkedin")
linkedin_search("mathieu  Mothay  Polene linkedin")
time.sleep(20)
linkedin_search("lisa  Hoch  Polene linkedin")
linkedin_search("juliette    Polene linkedin")
linkedin_search("alexa  Shapiro   bluefly linkedin")
linkedin_search("catherine  Kramvis  bluefly linkedin")
linkedin_search("peter  Dering  Peak Design linkedin")
time.sleep(20)
linkedin_search("jennifer  howell  Peak Design linkedin")
linkedin_search("Lawrence   Lander  Peak Design linkedin")
linkedin_search("jojo  Legnitto  Peak Design linkedin")
linkedin_search("David   Anhalt  Peak Design linkedin")
time.sleep(20)
linkedin_search("richard    LuminaSkin linkedin")
linkedin_search("darwish    LuminaSkin linkedin")
linkedin_search("Rob   Lamb   Crown and Caliber linkedin")
linkedin_search("eitan  Sisso   Daily Steals linkedin")
time.sleep(20)
linkedin_search("ryan  Gholson  Black Rifle Coffee Company  linkedin")
linkedin_search("holly  Frogley  McGee and Co  linkedin")
linkedin_search("Raina  Taylor   thirdlove linkedin")
linkedin_search("andy    happyskinco linkedin")
linkedin_search("emily  kapsner  Bandier linkedin")
time.sleep(20)
linkedin_search("logan  osborn  Bandier linkedin")
linkedin_search("sara  Duncan   Ooni Pizza Ovens  linkedin")
linkedin_search("kevin  Brown   Ooni Pizza Ovens  linkedin")
linkedin_search("john    Ooni Pizza Ovens  linkedin")
time.sleep(20)
linkedin_search("halla  Abushaqra   Ooni Pizza Ovens  linkedin")
linkedin_search("patrick    Ooni Pizza Ovens  linkedin")
linkedin_search("Lloyd   Ellman   Public Goods linkedin")
linkedin_search("hana  El Gamal  Public Goods linkedin")
time.sleep(20)
linkedin_search("joost    Public Goods linkedin")
linkedin_search("james  Brundage  Public Goods linkedin")
linkedin_search("gavin  Dogan  simplehuman  linkedin")
linkedin_search("Monte   Williams  Avocado Green Mattress linkedin")
linkedin_search("hannah  maguire  Avocado Green Mattress linkedin")
time.sleep(20)
linkedin_search("Roy  Kwon   calpaktravel linkedin")
linkedin_search("elizabeth    nativecos linkedin")
linkedin_search("james    credobeauty linkedin")
linkedin_search("carsen  Berry  buckmason linkedin")
time.sleep(20)
linkedin_search("Jordan   Freytag  trueleafmarket linkedin")
linkedin_search("ann    boll and branch linkedin")
linkedin_search("alexandra    boll and branch linkedin")
linkedin_search("ryan  ferros  boll and branch linkedin")
linkedin_search("steven  braim  boll and branch linkedin")
time.sleep(20)
linkedin_search("alia    boll and branch linkedin")
linkedin_search("hannah  Yampolsky  boll and branch linkedin")
linkedin_search("grace    misen linkedin")
linkedin_search("melissa  bell  Lovevery linkedin")
linkedin_search("rina  Patel   Lovevery linkedin")
time.sleep(20)
linkedin_search("andrew  Montgomery   Lovevery linkedin")
linkedin_search("alinda  Wit   Lovevery linkedin")
linkedin_search("Emily  sarver  Lovevery linkedin")
linkedin_search("shae  Amdor  Lovevery linkedin")
linkedin_search("salvador  Amdor  Lovevery linkedin")
time.sleep(20)
linkedin_search("Ray  Lee  Raycon linkedin")
linkedin_search("Richard   Rhee  Raycon linkedin")
linkedin_search("Jason   Lee  Raycon linkedin")
linkedin_search("mary  jarvis  Raycon linkedin")
linkedin_search("chris   bradley  Raycon linkedin")
time.sleep(20)
linkedin_search("Daniel   Song  Raycon linkedin")
linkedin_search("Wyatt   Sliman Boumedine  pax linkedin")
linkedin_search("daniel  Contos  White Fox Boutique  linkedin")
linkedin_search("stanton    White Fox Boutique  linkedin")
time.sleep(20)
linkedin_search("max  Wallace  tommyjohn linkedin")
linkedin_search("polly  Burke  nobullproject linkedin")
linkedin_search("eliza    Brinker and Eliza linkedin")
linkedin_search("brinker    Brinker and Eliza linkedin")
linkedin_search("justin  Crosbie  tula linkedin")
time.sleep(20)
linkedin_search("katrina    tula linkedin")
linkedin_search("mabel    tula linkedin")
linkedin_search("karyn    tula linkedin")
linkedin_search("jenny  lee  gaiam linkedin")
time.sleep(20)
linkedin_search("Matthew  Bernhardt  gaiam linkedin")
linkedin_search("robert  bros  merchology linkedin")
linkedin_search("kelly  countryman  merchology linkedin")
linkedin_search("Samuel   Kuchera  merchology linkedin")
time.sleep(20)
linkedin_search("abby  jacobs  merchology linkedin")
linkedin_search("Matthew   Christoff   merchology linkedin")
linkedin_search("kelsey  burggraff  merchology linkedin")
linkedin_search("brendan  Merriweather  brumate linkedin")
linkedin_search("amy  kelly  brumate linkedin")
time.sleep(20)
linkedin_search("jacob  Beaudrie  brumate linkedin")
linkedin_search("philip  poel  ember linkedin")
linkedin_search("Tom   Tejada  ember linkedin")
linkedin_search("Jolene  Abbott  ember linkedin")
linkedin_search("Brian  Donahue  ember linkedin")
time.sleep(20)
linkedin_search("zach  Horton  ember linkedin")
linkedin_search("chrissy    gldn linkedin")
linkedin_search("linda    gldn linkedin")
linkedin_search("zayyad   Wain  nixplay linkedin")
linkedin_search("ateeq    publicdesire linkedin")
time.sleep(20)
linkedin_search("tayyab    publicdesire linkedin")
linkedin_search("merle  Waterman   The Pros Closet linkedin")
linkedin_search("ryan    Go Chirp  linkedin")
linkedin_search("francesca  Ngatuvai  Go Chirp  linkedin")
linkedin_search("gregory  a  Magic Spoon linkedin")
time.sleep(20)
linkedin_search("gabi    Magic Spoon linkedin")
linkedin_search("elizabeth  lane  Magic Spoon linkedin")
linkedin_search("ana  castro  Magic Spoon linkedin")
linkedin_search("mark  Diaz   Magic Spoon linkedin")
linkedin_search("dhiya    Magic Spoon linkedin")
time.sleep(20)
linkedin_search("alexandra    Magic Spoon linkedin")
linkedin_search("cortney    Magic Spoon linkedin")
linkedin_search("sydney  Dymond   Magic Spoon linkedin")
linkedin_search("ezra  Firestone  BOOM by Cindy Joseph linkedin")
linkedin_search("pepijn    BOOM by Cindy Joseph linkedin")
time.sleep(20)
linkedin_search("kevin  Kuntz  BOOM by Cindy Joseph linkedin")
linkedin_search("colleen  Taylor  BOOM by Cindy Joseph linkedin")
linkedin_search("bruce    BOOM by Cindy Joseph linkedin")
linkedin_search("James  Sweeten  Turtle Beach linkedin")
time.sleep(20)
linkedin_search("olivia  Alvarez  SodaStream linkedin")
linkedin_search("andrea  Benegas  Sakara Life linkedin")
linkedin_search("Carly   Brand  Sakara Life linkedin")
linkedin_search("mathew    Sakara Life linkedin")
time.sleep(20)
linkedin_search("alejandro  Martorell  ALOHAS linkedin")
linkedin_search("dylon  york  CORKCICLE linkedin")
linkedin_search("zachary  Gentry  Helix Sleep linkedin")
linkedin_search("ashley    Helix Sleep linkedin")
linkedin_search("ariel  kaye  Helix Sleep linkedin")
time.sleep(20)
linkedin_search("pj  Worsfold  Deadstock linkedin")
linkedin_search("Mae   Steigler  Organifi linkedin")
linkedin_search("will    Organifi linkedin")
linkedin_search("chase    Organifi linkedin")
time.sleep(20)
linkedin_search("richard  Canneman  Ekster linkedin")
linkedin_search("stephanie    Ekster linkedin")
